-- CREAR LAS TABLAS PRINCIPALES

-- TABLA DE USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    CONTRASEÑA VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO)
);
COMMENT ON TABLE USUARIOS IS 'TABLA QUE CONTIENE LOS USUARIOS REGISTRADOS';
COMMENT ON COLUMN USUARIOS.ID_USUARIO IS 'IDENTIFICADOR ÚNICO DEL USUARIO';
COMMENT ON COLUMN USUARIOS.NOMBRE IS 'NOMBRE DEL USUARIO';
COMMENT ON COLUMN USUARIOS.CORREO IS 'CORREO ELECTRÓNICO DEL USUARIO';
COMMENT ON COLUMN USUARIOS.CONTRASEÑA IS 'CONTRASEÑA DEL USUARIO';

-- TABLA DE ORGANIZADORES
CREATE TABLE ORGANIZADORES (
    ID_ORGANIZADOR NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    CONTACTO VARCHAR2(150) NOT NULL,
    CONSTRAINT PK_ORGANIZADORES PRIMARY KEY (ID_ORGANIZADOR)
);
COMMENT ON TABLE ORGANIZADORES IS 'TABLA QUE CONTIENE LOS ORGANIZADORES DE EVENTOS';
COMMENT ON COLUMN ORGANIZADORES.ID_ORGANIZADOR IS 'IDENTIFICADOR ÚNICO DEL ORGANIZADOR';
COMMENT ON COLUMN ORGANIZADORES.NOMBRE IS 'NOMBRE DEL ORGANIZADOR';
COMMENT ON COLUMN ORGANIZADORES.CONTACTO IS 'INFORMACIÓN DE CONTACTO DEL ORGANIZADOR';

-- TABLA DE CATEGORÍAS
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA NUMBER,
    NOMBRE_CATEGORIA VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID_CATEGORIA)
);
COMMENT ON TABLE CATEGORIAS IS 'TABLA QUE CONTIENE LAS CATEGORÍAS DE EVENTOS';
COMMENT ON COLUMN CATEGORIAS.ID_CATEGORIA IS 'IDENTIFICADOR ÚNICO DE LA CATEGORÍA';
COMMENT ON COLUMN CATEGORIAS.NOMBRE_CATEGORIA IS 'NOMBRE DE LA CATEGORÍA';

-- TABLA DE UBICACIONES
CREATE TABLE UBICACIONES (
    ID_UBICACION NUMBER,
    TIPO_UBICACION VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_UBICACIONES PRIMARY KEY (ID_UBICACION),
    CONSTRAINT CHK_TIPO_UBICACION CHECK (TIPO_UBICACION IN ('Online', 'Presencial'))
);
COMMENT ON TABLE UBICACIONES IS 'TABLA QUE CONTIENE LAS UBICACIONES DE LOS EVENTOS';
COMMENT ON COLUMN UBICACIONES.ID_UBICACION IS 'IDENTIFICADOR ÚNICO DE LA UBICACIÓN';
COMMENT ON COLUMN UBICACIONES.TIPO_UBICACION IS 'TIPO DE UBICACIÓN (ONLINE O PRESENCIAL)';
COMMENT ON COLUMN UBICACIONES.DIRECCION IS 'DIRECCIÓN DE LA UBICACIÓN';

-- TABLA DE EVENTOS
CREATE TABLE EVENTOS (
    ID_EVENTO NUMBER,
    NOMBRE VARCHAR2(150) NOT NULL,
    FECHA DATE NOT NULL,
    DURACION NUMBER NOT NULL, 
    ID_UBICACION NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_ORGANIZADOR NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(150) NOT NULL,
    CONSTRAINT PK_EVENTOS PRIMARY KEY (ID_EVENTO),
    CONSTRAINT FK_EVENTOS_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES(ID_UBICACION),
    CONSTRAINT FK_EVENTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT FK_EVENTOS_ORGANIZADOR FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADORES(ID_ORGANIZADOR)
);
COMMENT ON TABLE EVENTOS IS 'TABLA QUE CONTIENE LOS EVENTOS DISPONIBLES';
COMMENT ON COLUMN EVENTOS.ID_EVENTO IS 'IDENTIFICADOR ÚNICO DEL EVENTO';
COMMENT ON COLUMN EVENTOS.NOMBRE IS 'NOMBRE DEL EVENTO';
COMMENT ON COLUMN EVENTOS.FECHA IS 'FECHA DEL EVENTO';
COMMENT ON COLUMN EVENTOS.DURACION IS 'DURACIÓN DEL EVENTO EN HORAS';
COMMENT ON COLUMN EVENTOS.ID_UBICACION IS 'IDENTIFICADOR DE LA UBICACIÓN DEL EVENTO';
COMMENT ON COLUMN EVENTOS.ID_CATEGORIA IS 'IDENTIFICADOR DE LA CATEGORÍA DEL EVENTO';
COMMENT ON COLUMN EVENTOS.ID_ORGANIZADOR IS 'IDENTIFICADOR DEL ORGANIZADOR DEL EVENTO';
COMMENT ON COLUMN EVENTOS.DESCRIPCION IS 'DESCRIPCIÓN DEL EVENTO';

-- TABLA DE INSCRIPCIONES (RELACIÓN N:M ENTRE USUARIOS Y EVENTOS)
CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCIONES NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_EVENTO NUMBER NOT NULL,
    FECHA_INSCRIPCION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_INSCRIPCIONES PRIMARY KEY (ID_INSCRIPCIONES),
    CONSTRAINT FK_INSCRIPCIONES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_INSCRIPCIONES_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO)
);
COMMENT ON TABLE INSCRIPCIONES IS 'TABLA QUE CONTIENE LAS INSCRIPCIONES DE LOS USUARIOS A LOS EVENTOS';
COMMENT ON COLUMN INSCRIPCIONES.ID_INSCRIPCION IS 'IDENTIFICADOR ÚNICO DE LA INSCRIPCIÓN';
COMMENT ON COLUMN INSCRIPCIONES.ID_USUARIO IS 'IDENTIFICADOR DEL USUARIO QUE SE INSCRIBE';
COMMENT ON COLUMN INSCRIPCIONES.ID_EVENTO IS 'IDENTIFICADOR DEL EVENTO AL QUE SE INSCRIBE EL USUARIO';
COMMENT ON COLUMN INSCRIPCIONES.FECHA_INSCRIPCION IS 'FECHA EN QUE SE REALIZA LA INSCRIPCIÓN';
